services:

  postgres:
    image: postgres:16
    container_name: pg-auth
    platform: linux/amd64
    environment:
      POSTGRES_DB: cloud
      POSTGRES_USER: cloud
      POSTGRES_PASSWORD: cloud
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/newbase.sql:/docker-entrypoint-initdb.d/01_newbase.sql:ro
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cloud -d cloud -h 127.0.0.1 -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  api:
    build:
      context: ./app
      args:
        MAVEN_CONFIG: /root/.m2
    container_name: cloud-api
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cloud
      SPRING_DATASOURCE_USERNAME: cloud
      SPRING_DATASOURCE_PASSWORD: cloud
    volumes:
      - photo-uploads:/app/uploads/photos
    networks:
      - app-network
    restart: unless-stopped

  map:
    image: maptiler/tileserver-gl:latest
    container_name: osm-map
    ports:
      - "8081:8080"
    volumes:
      - ./map:/data
    # On remplace la variable d'env MBTILES_FILE par la commande config
    command: -c /data/config.json
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
  photo-uploads:
