spring.application.name=app
server.port=8080

spring.datasource.url=jdbc:postgresql://postgres:5432/cloud
spring.datasource.username=cloud
spring.datasource.password=cloud
spring.datasource.driver-class-name=org.postgresql.Driver

# IMPORTANT: Désactiver les modifications automatiques du schéma
# Car le schéma est géré manuellement via le script SQL
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Database initialization
spring.sql.init.mode=never

# Disable Spring Security for development
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration